version: "3.9"

services:
  bot:
    build: ./bot
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
